project: 
  type: website

website:
  title: UnArchaeology 2024
  site-url: "https://unarchaeology.nl"
  repo-url: "https://github.com/bbartholdy/unarchaeology.nl"
  sidebar: 
    style: docked
    tools: 
      - icon: github
        href: "https://github.com/bbartholdy/unarchaeology.nl"
        aria-label: GitHub
    contents: 
      - href: index.qmd
        text: Home
      - section: Programme
        contents: 
          - href: programme.qmd
            text: Schedule
          - href: workshops.qmd
            text: Workshops
          - href: presentations.qmd
            text: Presentations
      - href: registration.qmd
      - href: marketplace.qmd
      - href: venue.qmd

format: 
  html: 
    css: custom.css
    theme:
      dark: mistral.scss
      light: claude.scss